# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: single-cell-tx-benchmark-0.1.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - seaborn
  - scikit-learn
  - statsmodels
  - pytables
  - conda-forge::python-igraph 
  - vtraag::louvain
  - pip:
    - ipykernel
    - scanpy
    - numba==0.43.1
    - mnnpy
    - annoy==1.15.2
    - bbknn
    - papermill
    - MulticoreTSNE
