name: single_sample_param_exploration

on: 
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: CPU Check
      run: cat /proc/cpuinfo
    - name: Install Nextflow
      run: |
        export NXF_VER='21.04.3'
        wget -qO- get.nextflow.io | bash
        sudo mv nextflow /usr/local/bin/
    - name: Get sample data
      run: |
        wget https://raw.githubusercontent.com/aertslab/SCENICprotocol/master/example/sample_data_tiny.tar.gz
        tar xzvf sample_data_tiny.tar.gz
    - name: Run single_sample_param_exploration test
      run: |
        nextflow run ${GITHUB_WORKSPACE} -profile single_sample,test__single_sample_param_exploration,test__compute_resources,docker -entry single_sample -ansi-log false
        cat .nextflow.log

